version: '3.8'

services:
  fastapi:
    build: .
    container_name: employee-knowledge-quiz-api
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - test
    restart: always
    networks:
      - postgres

  postgres:
    container_name: main-db-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres

  test:
    container_name: test-db-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: ${TEST_POSTGRES_HOST}
    ports:
      - "5433:5433"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres: